name: Resuable workflow

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : check file content
      run : |
       if grep -R "https://github.com/${{github.repository}}" /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/list.txt
       then
        echo "VALID_URL=true" >> $GITHUB_ENV
        echo "string exists"
       else
       echo "VALID_URL=false" >> $GITHUB_ENV
       echo " string not found"
       fi
      
    - name : zip files
      run : |
       echo ${{ env.VALID_URL }}
       sudo ls -ltr /home/runner/work
       zip -r /home/runner/work/${{ github.event.repository.name }}  /home/runner/work/${{ github.event.repository.name }}
    
    - name: REST API with curl
      env:
        filename : $md
      run: |
       curl -H "Content-Type: multipart/form-data" -F "file=@/home/runner/work/${{ github.event.repository.name }}.zip" -F "isMarkDown=$filename" http://192.168.1.105:8080/api/upload
