name: Resuable workflow

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : check if git url is valid
      run : |
       if grep -R "https://github.com/${{github.repository}}" /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/list.txt
       then
        echo "VALID_URL=true" >> $GITHUB_ENV
        echo "valid url"
       else
       echo "VALID_URL=false" >> $GITHUB_ENV
       echo "invalid url"
       fi 
        if:github.ref == 'refs/heads/master'
        echo "UAT env key" ${{secrets.ENV_UAT_API_SECRET_KEY}}
    - name : zip files and publish using curl
      run : |
       echo "${{secrets.API_KEY}}"
       if [[ ${{ env.VALID_URL }} == true ]]
         then
       sudo ls -ltr /home/runner/work
       zip -r /home/runner/work/${{ github.event.repository.name }}  /home/runner/work/${{ github.event.repository.name }}
       curl -H "Content-Type: multipart/form-data" -F "file=@/home/runner/work/${{ github.event.repository.name }}.zip" -F "isMarkDown=$filename" ${{secrets.API_URL}}
         else
       echo "publishing failed"  
       fi
   
