name: Resuable workflow

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Clone reusable-workflow  repository
      uses: actions/checkout@v3
      with:
        repository: sanknoorsachin/reusable-workflow
        path: resources/reusable-workflow/

        
    - name : check if git url is valid
      run : |
       ::add-mask::
       ls -ltr resources/reusable-workflow/
       
       if grep -R "https://github.com/${{github.repository}}" resources/reusable-workflow/list.yml
       then
        echo "VALID_URL=true" >> $GITHUB_ENV
        echo "valid url"
       else
       echo "VALID_URL=false" >> $GITHUB_ENV
       echo "invalid url"
       fi 
       
        
    - name : zip files and publish using curl
      run : |
       echo "${{secrets.REPO_API_KEY}}"
     
       if [[ ${{ env.VALID_URL }} == true ]]
         then
       sudo ls -ltr /home/runner/work
       zip -r /home/runner/work/${{ github.event.repository.name }}  /home/runner/work/${{ github.event.repository.name }}
       curl -H "Content-Type: multipart/form-data" -F "file=@/home/runner/work/${{ github.event.repository.name }}.zip" -F "isMarkDown=$filename" ${{secrets.API_URL}}
         else
       echo "publishing failed"  
       fi
   
